@host = http://localhost:5238

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "djhon@gmail.com",
    "password": "John1234!"
}
